apiVersion: v1
kind: ConfigMap
metadata:
  name: yelp-config
  namespace: yelp
data:
  MONGODB_DB: "yelp_lab2"

  KAFKA_BOOTSTRAP_SERVERS: "kafka:9092"
  KAFKA_REVIEW_CREATED_TOPIC: "review.created"
  KAFKA_REVIEW_UPDATED_TOPIC: "review.updated"
  KAFKA_REVIEW_DELETED_TOPIC: "review.deleted"

  ALGORITHM: "HS256"
  ACCESS_TOKEN_EXPIRE_MINUTES: "1440"

  OLLAMA_HOST: "http://host.docker.internal:11434"
  OLLAMA_MODEL: "llama3.2"

  FRONTEND_PORT: "5173"
  BACKEND_PORT: "8000"
  MONGO_PORT: "27017"
  ZOOKEEPER_CLIENT_PORT: "2181"
  KAFKA_PORT: "9092"